# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import symbol_detector_pb2 as symbol__detector__pb2


class SymbolDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/symbol_detector.SymbolDetector/Predict',
                request_serializer=symbol__detector__pb2.PredictRequest.SerializeToString,
                response_deserializer=symbol__detector__pb2.PredictResponse.FromString,
                )
        self.ScanBlueprint = channel.unary_unary(
                '/symbol_detector.SymbolDetector/ScanBlueprint',
                request_serializer=symbol__detector__pb2.ScanRequest.SerializeToString,
                response_deserializer=symbol__detector__pb2.ScanResponse.FromString,
                )


class SymbolDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """RPC 1: Simple comparison (what we have now)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanBlueprint(self, request, context):
        """RPC 2: The Bobyard Special (New!)
        Takes a reference symbol and a full page, returns multiple locations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SymbolDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=symbol__detector__pb2.PredictRequest.FromString,
                    response_serializer=symbol__detector__pb2.PredictResponse.SerializeToString,
            ),
            'ScanBlueprint': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanBlueprint,
                    request_deserializer=symbol__detector__pb2.ScanRequest.FromString,
                    response_serializer=symbol__detector__pb2.ScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'symbol_detector.SymbolDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SymbolDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/symbol_detector.SymbolDetector/Predict',
            symbol__detector__pb2.PredictRequest.SerializeToString,
            symbol__detector__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScanBlueprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/symbol_detector.SymbolDetector/ScanBlueprint',
            symbol__detector__pb2.ScanRequest.SerializeToString,
            symbol__detector__pb2.ScanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
