# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: symbol_detector.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15symbol_detector.proto\x12\x0fsymbol_detector\">\n\x0ePredictRequest\x12\x17\n\x0freference_image\x18\x01 \x01(\x0c\x12\x13\n\x0bquery_image\x18\x02 \x01(\x0c\"N\n\x0fPredictResponse\x12\x18\n\x10similarity_score\x18\x01 \x01(\x02\x12\x10\n\x08is_match\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"?\n\x0bScanRequest\x12\x17\n\x0freference_image\x18\x01 \x01(\x0c\x12\x17\n\x0f\x62lueprint_image\x18\x02 \x01(\x0c\"Q\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x02\"N\n\x0cScanResponse\x12-\n\x07matches\x18\x01 \x03(\x0b\x32\x1c.symbol_detector.BoundingBox\x12\x0f\n\x07message\x18\x02 \x01(\t2\xac\x01\n\x0eSymbolDetector\x12L\n\x07Predict\x12\x1f.symbol_detector.PredictRequest\x1a .symbol_detector.PredictResponse\x12L\n\rScanBlueprint\x12\x1c.symbol_detector.ScanRequest\x1a\x1d.symbol_detector.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'symbol_detector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=42
  _globals['_PREDICTREQUEST']._serialized_end=104
  _globals['_PREDICTRESPONSE']._serialized_start=106
  _globals['_PREDICTRESPONSE']._serialized_end=184
  _globals['_SCANREQUEST']._serialized_start=186
  _globals['_SCANREQUEST']._serialized_end=249
  _globals['_BOUNDINGBOX']._serialized_start=251
  _globals['_BOUNDINGBOX']._serialized_end=332
  _globals['_SCANRESPONSE']._serialized_start=334
  _globals['_SCANRESPONSE']._serialized_end=412
  _globals['_SYMBOLDETECTOR']._serialized_start=415
  _globals['_SYMBOLDETECTOR']._serialized_end=587
# @@protoc_insertion_point(module_scope)
